spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/IntelligentNursingHomeManagementSystem?useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 333222
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false